Adds singleton methods to Client class. These methods allow to query endpoints classes
erikgrueter1/yelp-fusion pull request #6
Opened 2018-07-18 05:48 UTC by bernardogalindo

#### what?
Adds backward compatibility with old yelp gem.

Adds singleton methods to client instance object ensuring that only this object can query the endpoints. 

* Adds Endpoints(Search, Business, Phone) singleton methods to Client class instance
* Extracts singleton into a module

#### why?

Old yelp gem supports these queries.

```ruby
  client =. Yelp::Client.new(YOUR_API_KEY)
  client.search('San Francisco')
  client.search_by_coordinates(coordinates, params, locale)
  client.business('yelp-san-francisco')
  client.phone_search('+15555555555')
```

#### issue related

https://github.com/erikgrueter1/yelp-fusion/issues/5

2018-07-18 12:11 UTC, erikgrueter1 commented
@lkatzman Please review

2018-07-20 17:15 UTC, erikgrueter1 requested changes
@bernardogalindo Are the tests passing?

2018-07-20 17:15 UTC, erikgrueter1 commented on lib/yelp/fusion/singleton.rb
> +        # yelp
@bernardogalindo Remove 'yelp' note

2018-07-20 17:15 UTC, erikgrueter1 commented on lib/yelp/fusion/singleton.rb
> +      REQUEST_CLASSES = [ Yelp::Fusion::Endpoint::Search,
@bernardogalindo Space in Array

2018-07-23 16:04 UTC, bernardogalindo commented
Hello @erikgrueter1, Hope you are doing great.
Tests are passing, are they failing in your side? 
![captura de pantalla 2018-07-23 a la s 11 02 07](https://user-images.githubusercontent.com/208863/43088550-0b31515a-8e68-11e8-961d-3596815d17a3.png)

2018-07-24 15:21 UTC, lkatzman commented
HI @bernardogalindo we opened a new pull request with your changes and commits in it, and we will close yours. Thank you for contributing!

2018-07-24 16:56 UTC, bernardogalindo commented
hi @lkatzman thanks. When do you think the new pr can be merge into master?

2018-07-27 02:46 UTC, erikgrueter1 commented
@bernardogalindo We hope to merge soon. Having @lkatzman do some final testing. Are you using this in a production Rails application?

2018-07-27 18:58 UTC, erikgrueter1 commented
@bernardogalindo We will get your commits in shortly in #7

2018-07-27 18:59 UTC, closed without merging

2018-07-27 21:51 UTC, bernardogalindo commented
@erikgrueter1 thanks. I'm using the old Yelp gem version in production. We are actually using my changes to mitigate issues but if you release  a new version will be better to use the official implementation.